server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: blog-service
          uri: lb://BLOG-SERVICE
          predicates:
            - Path=/api/blog/**,
        
